[package]
name = "device_manager"
description = "manage device specific settings"
version = "0.1.0"
edition = "2021"

[dependencies]
serde ={ workspace = true}
sysinfo = "0.30.13"
ts-rs = {workspace = true}
