[package]
name = "filesystem"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
filesize = "0.2.0"
fs_extra = "1.3.0"
path-absolutize = "3.1.1"
serde = { version = "1.0.204", features = ["derive"] }
ts-rs = "9.0.1"
walkdir = "2.5.0"
