[package]
name = "desktop_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { workspace = true, features = ["csr"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
thaw = { workspace = true, features = ["csr"] }
leptos-remix-icon = { workspace = true }
leptos_router = { workspace = true }
leptos-use = { workspace = true }
leptos_toaster = { workspace = true, features = ["csr"] }
filesync_icons = { path = "../icons", version = "*" }
leptos_reactive = { workspace = true }
tauri-wasm-bindgen = { workspace = true }
leptos-qr = { git = "https://github.com/opeolluwa/leptos-qr", version = "0.2.0" }
